volumes:
  users.db:
  accounts.db:
  cache:

services:
  users.webapi:
    image: mikeswallet.users
    container_name: users.webapi
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      ASPNETCORE_HTTP_PORTS: "8888"
    build:
      context: .
      dockerfile: MikesWallet.Users.WebApi/Dockerfile
    restart: no
    ports:
      - "8888:8888"
    
  users.database:
    image: postgres:16-bullseye
    container_name: users.database
    environment:
      - POSTGRES_DB=UsersServiceDb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345678
    restart: no
    volumes:
      - users.db:/var/lib/postgresql/data
  
  accounts.webapi:
    image: mikeswallet.accounts
    container_name: accounts.webapi
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      ASPNETCORE_HTTP_PORTS: "9999"
    build:
      context: .
      dockerfile: MikesWallet.Accounts.WebApi/Dockerfile
    restart: no
    ports:
      - "9999:9999"
  
  accounts.database:
    image: postgres:16-bullseye
    container_name: accounts.database
    environment:
      - POSTGRES_DB=AccountsServiceDb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345678
    restart: no
    volumes:
      - accounts.db:/var/lib/postgresql/data
  
  cache:
    image: redis:latest
    container_name: redis.cache
    restart: no
    volumes:
      - cache:/data
  
  redis-ui:
    image: ghcr.io/joeferner/redis-commander:latest
    container_name: redis.ui
    environment:
      - REDIS_HOSTS=local:redis.cache
    ports:
      - "8081:8081"
    restart: no